package com.entropylab.ui;

import com.entropylab.config.ConfigManager;
import com.entropylab.model.MockMapping;
import com.entropylab.util.PathUtil;
import javafx.beans.property.SimpleBooleanProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;
import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;
import javafx.scene.control.ButtonBar;
import javafx.scene.control.ButtonType;
import javafx.scene.control.Dialog;
import javafx.scene.control.Label;
import javafx.scene.control.TableColumn;
import javafx.scene.control.TableView;
import javafx.scene.control.TextField;
import javafx.scene.control.cell.CheckBoxTableCell;
import javafx.scene.layout.GridPane;
import javafx.scene.layout.HBox;
import javafx.scene.layout.Priority;
import javafx.scene.layout.VBox;
import javafx.stage.FileChooser;
import javafx.stage.Window;

import java.io.File;
import java.util.List;

public class MockManagementView extends VBox {

    private final TableView<MockMapping> tableView;
    private final ObservableList<MockMapping> mockList;
    private final Button addMockButton;

    // Delete functionality deferred to a future milestone / optional.

    public MockManagementView() {
        setPadding(new Insets(16));
        setSpacing(12);

        addMockButton = new Button("Add Mock");
        addMockButton.setId("addMockButton");
        addMockButton.setOnAction(e -> showAddMockDialog());

        HBox toolbar = new HBox(addMockButton);
        toolbar.setAlignment(Pos.CENTER_LEFT);

        List<MockMapping> existingMocks = ConfigManager.getInstance().getConfig() != null
                && ConfigManager.getInstance().getConfig().getMockMappings() != null
                ? ConfigManager.getInstance().getConfig().getMockMappings()
                : List.of();

        mockList = FXCollections.observableArrayList(existingMocks);
        tableView = new TableView<>(mockList);
        tableView.setEditable(true);
        tableView.setColumnResizePolicy(TableView.CONSTRAINED_RESIZE_POLICY);

        TableColumn<MockMapping, String> localPathCol = new TableColumn<>("Local Path");
        localPathCol.setCellValueFactory(data -> new SimpleStringProperty(data.getValue().getLocalPath()));
        localPathCol.setEditable(false);
        localPathCol.setPrefWidth(220);

        TableColumn<MockMapping, String> filePathCol = new TableColumn<>("File Path");
        filePathCol.setCellValueFactory(data -> new SimpleStringProperty(data.getValue().getFilePath()));
        filePathCol.setEditable(false);
        filePathCol.setPrefWidth(300);

        TableColumn<MockMapping, String> autoGenCol = new TableColumn<>("Auto-Generated");
        autoGenCol.setCellValueFactory(data -> new SimpleStringProperty(data.getValue().isAutoGenerated() ? "Yes" : "No"));
        autoGenCol.setEditable(false);
        autoGenCol.setPrefWidth(120);

        TableColumn<MockMapping, Boolean> enabledCol = new TableColumn<>("Enabled");
        enabledCol.setCellValueFactory(param -> {
            MockMapping mapping = param.getValue();
            SimpleBooleanProperty prop = new SimpleBooleanProperty(mapping.isEnabled());
            prop.addListener((obs, oldVal, newVal) -> {
                mapping.setEnabled(newVal);
                ConfigManager.getInstance().save();
            });
            return prop;
        });
        enabledCol.setCellFactory(CheckBoxTableCell.forTableColumn(enabledCol));
        enabledCol.setEditable(true);
        enabledCol.setPrefWidth(80);
        enabledCol.setMaxWidth(100);

        tableView.getColumns().addAll(localPathCol, filePathCol, autoGenCol, enabledCol);
        VBox.setVgrow(tableView, Priority.ALWAYS);

        getChildren().addAll(toolbar, tableView);
    }

    public void showAddMockDialog() {
        Dialog<ButtonType> dialog = buildAddMockDialog(null);
        dialog.showAndWait();
    }

    public Dialog<ButtonType> buildAddMockDialog(File initialFile) {
        Dialog<ButtonType> dialog = new Dialog<>();
        dialog.setTitle("Add Mock");
        dialog.setHeaderText("Configure Mock Endpoint");

        ThemeManager.getInstance().styleDialog(dialog);

        ButtonType addButtonType = new ButtonType("Add", ButtonBar.ButtonData.OK_DONE);
        dialog.getDialogPane().getButtonTypes().addAll(addButtonType, ButtonType.CANCEL);

        GridPane grid = new GridPane();
        grid.setHgap(10);
        grid.setVgap(10);
        grid.setPadding(new Insets(20, 20, 10, 10));

        TextField localPathField = new TextField();
        localPathField.setId("mockLocalPathField");
        localPathField.setPromptText("/api/example");

        Label selectedFileLabel = new Label(initialFile != null ? initialFile.getAbsolutePath() : "No file selected");
        selectedFileLabel.setId("selectedFileLabel");

        final File[] chosenFile = new File[]{initialFile};

        Button chooseFileButton = new Button("Choose File...");
        chooseFileButton.setId("chooseMockFileButton");
        chooseFileButton.setOnAction(e -> {
            FileChooser fileChooser = new FileChooser();
            fileChooser.setTitle("Choose Mock JSON File");
            fileChooser.getExtensionFilters().add(new FileChooser.ExtensionFilter("JSON Files (*.json)", "*.json"));
            Window window = dialog.getDialogPane().getScene() != null ? dialog.getDialogPane().getScene().getWindow() : null;
            File file = fileChooser.showOpenDialog(window);
            if (file != null) {
                chosenFile[0] = file;
                selectedFileLabel.setText(file.getAbsolutePath());
            }
        });

        HBox fileBox = new HBox(8, chooseFileButton, selectedFileLabel);
        fileBox.setAlignment(Pos.CENTER_LEFT);

        grid.add(new Label("Local Path:"), 0, 0);
        grid.add(localPathField, 1, 0);
        grid.add(new Label("Mock File:"), 0, 1);
        grid.add(fileBox, 1, 1);

        dialog.getDialogPane().setContent(grid);

        Button addButton = (Button) dialog.getDialogPane().lookupButton(addButtonType);
        addButton.addEventFilter(ActionEvent.ACTION, event -> {
            String localPath = localPathField.getText();
            boolean success = addMock(localPath, chosenFile[0]);
            if (!success) {
                event.consume();
            }
        });

        return dialog;
    }

    public boolean addMock(String localPath, File selectedFile) {
        if (localPath == null || localPath.trim().isEmpty()) {
            showThemedAlert(Alert.AlertType.WARNING, "Validation Error", "Local Path is required");
            return false;
        }

        String normalizedLocalPath = PathUtil.normalize(localPath.trim());
        boolean duplicate = ConfigManager.getInstance().getConfig().getMockMappings().stream()
                .anyMatch(m -> m.getLocalPath() != null && PathUtil.normalize(m.getLocalPath()).equals(normalizedLocalPath));

        if (duplicate) {
            showThemedAlert(Alert.AlertType.WARNING, "Duplicate Mock", "A mock for this path already exists; edit or delete it first");
            return false;
        }

        if (selectedFile == null) {
            showThemedAlert(Alert.AlertType.WARNING, "Validation Error", "Please choose a .json file");
            return false;
        }

        MockMapping mapping = new MockMapping();
        mapping.setId(ConfigManager.getInstance().nextMockMappingId());
        mapping.setLocalPath(normalizedLocalPath);
        mapping.setFilePath(selectedFile.getAbsolutePath());
        mapping.setEnabled(true);
        mapping.setAutoGenerated(false);

        ConfigManager.getInstance().getConfig().getMockMappings().add(mapping);
        mockList.add(mapping);
        ConfigManager.getInstance().save();
        return true;
    }

    protected void showThemedAlert(Alert.AlertType type, String title, String content) {
        Alert alert = new Alert(type);
        alert.setTitle(title);
        alert.setHeaderText(null);
        alert.setContentText(content);
        ThemeManager.getInstance().styleDialog(alert);
        alert.showAndWait();
    }

    public TableView<MockMapping> getTableView() {
        return tableView;
    }

    public ObservableList<MockMapping> getMockList() {
        return mockList;
    }

    public void refresh() {
        List<MockMapping> mappings = ConfigManager.getInstance().getConfig() != null
                && ConfigManager.getInstance().getConfig().getMockMappings() != null
                ? ConfigManager.getInstance().getConfig().getMockMappings()
                : List.of();
        mockList.setAll(mappings);
        tableView.refresh();
    }

    public Button getAddMockButton() {
        return addMockButton;
    }
}
