# Default Environment Properties for EntropyLab
DEVELOPER_NAME=Abdur Rahman
DEVELOPER_GITHUB=https://github.com/AR-Fahim
DEVELOPER_LINKEDIN=https://linkedin.com/in/
DEVELOPER_TWITTER=https://x.com/
GITHUB_REPO_URL=https://github.com/AR-Fahim/EntropyLab
APP_DOCS_URL=https://github.com/AR-Fahim/EntropyLab/blob/main/docs/00-MANUAL-INDEX.md
